services:
  # Backend API Service
  - type: web
    name: project-hub-backend
    env: node
    plan: starter
    buildCommand: ./scripts/build.sh
    startCommand: npm run migration:run:prod && npm run start:prod
    healthCheckPath: /health
    buildFilter:
      paths:
      - backend/**
      ignoredPaths:
      - backend/docs/**
      - backend/test/**
      - backend/README.md
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: project-hub-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 15m
      - key: JWT_REFRESH_EXPIRES_IN
        value: 7d
      - key: FRONTEND_URL
        value: myprojecthub.vercel.app
      - key: THROTTLE_TTL
        value: 60
      - key: THROTTLE_LIMIT
        value: 100
      - key: HUGGING_FACE_API_KEY
        sync: false
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: REDIS_URL
        fromService:
          type: redis
          name: project-hub-redis
          property: connectionString

  # PostgreSQL Database
databases:
  - name: project-hub-db
    databaseName: project_hub
    user: project_hub_user
    plan: starter

  # Redis Cache
  - name: project-hub-redis
    plan: starter