import {
  IsString,
  IsNumber,
  IsBoolean,
  IsArray,
  IsObject,
  IsOptional,
  Min,
  Max,
} from 'class-validator';
import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';

export class AssistantResponseDto {
  @ApiProperty({
    description: 'The AI assistant response text',
    example:
      'A literature review is a comprehensive survey of scholarly sources on a specific topic...',
  })
  @IsString()
  response: string;

  @ApiProperty({
    description: 'AI confidence score for the response',
    example: 0.85,
    minimum: 0,
    maximum: 1,
  })
  @IsNumber()
  @Min(0)
  @Max(1)
  confidenceScore: number;

  @ApiProperty({
    description: 'Source references used to generate the response',
    example: [
      'FYP Guidelines 2024',
      'Research Methodology Handbook',
      'Academic Writing Guide',
    ],
    type: [String],
  })
  @IsArray()
  @IsString({ each: true })
  sources: string[];

  @ApiProperty({
    description: 'Conversation ID this response belongs to',
    example: '123e4567-e89b-12d3-a456-426614174000',
  })
  @IsString()
  conversationId: string;

  @ApiProperty({
    description: 'Unique message ID for this response',
    example: '456e7890-e89b-12d3-a456-426614174001',
  })
  @IsString()
  messageId: string;

  @ApiProperty({
    description: 'Whether this response was generated by AI or fallback system',
    example: true,
  })
  @IsBoolean()
  fromAI: boolean;

  @ApiPropertyOptional({
    description: 'Suggested follow-up questions',
    example: [
      'How do I structure my literature review?',
      'What citation style should I use?',
      'How many sources should I include?',
    ],
    type: [String],
  })
  @IsOptional()
  @IsArray()
  @IsString({ each: true })
  suggestedFollowUps?: string[];

  @ApiPropertyOptional({
    description: 'Suggestion to escalate to human support',
    example:
      'For more detailed guidance on your specific research area, consider contacting your supervisor.',
  })
  @IsOptional()
  @IsString()
  escalationSuggestion?: string;

  @ApiProperty({
    description: 'Response metadata including processing information',
    example: {
      processingTime: 1500,
      language: 'en',
      category: 'methodology',
      requiresHumanReview: false,
    },
  })
  @IsObject()
  metadata: {
    processingTime: number;
    language: string;
    category: string;
    requiresHumanReview?: boolean;
  };
}
